origin_url: "https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=freudenmann&file=TINF23B1"
blacklist:
  - STUV-ADA 3 (freiwilliger Zusatz)
  - angewandtes Projektmanagement
  - Interaktive Systeme (KI & IS)
  - Bildverarbeitung (KI & BV)
  - e Business
  - .Grundlagen der KI (KI & BV)
  - Evolutionäre Algorithmen
  - Entwurf mobiler Applikationen
  - Nachklausuren  (120 min)
